### ISSUE TITLE
Could not complete Lab4

### ISSUE THREAD

**Issue by JuanVargas** [JuliaAI/DataScienceTutorials.jl#184]
Hi Folks,

I tried several times to complete MLJ Lab4. I tried multiple ways to get running the BayesianQDA and the KNN classifier as shown in Lab4 code but in both cases the code always returned errors when defining the classifiers as in

KNNClassifier = @load KNNClassifier
BayesianQDA = @load BayesianQDA pkg=ScikitLearn

I was hoping to adopt Julia and MLJ for my ML projects, but after way too many errors I have reached the end of my rope. The platform and the MLJ library are too immature and it would be foolish to spend any more time discovering that this or that does not work.

If you can't fix the errors at least make sure that the documentation you make public is accurate by acknowledging what works and what does not work. .As it is now I had to do numerous fixes to get things done. Quite disappointing.

**Comment by ablaom** [comment]
Sorry to hear about your frustrations. 

Further action on your issue will require you to provide details. The tutorial has been tested with Julia 1.6 and the accompanying Julia environment without issues. Can you please post the stack trace for the errors you are encountering? Also helpful would be a report of the output of `using Pkg; Pkg.status()`.

**Comment by tlienart** [comment]
1. download the project folder linked to at the top of the page (this: https://raw.githubusercontent.com/juliaai/DataScienceTutorials.jl/gh-pages/__generated/ISL-lab-4.tar.gz)
2. start Julia >=1.6, `cd` to that folder then activate it
3. call `include("tutorial.jl")` and wait a bit

I did these exact three steps just now (using 1.7.2 but result would be the same with 1.6), and the output is (as shown on the website):

<details>
```
(@v1.7) pkg> activate .
  Activating project at `~/Downloads/ISL-lab-4`

julia> include("tutorial.jl")
[ Info: Precompiling MLJ [add582a8-e3ab-11e8-2d5e-e98b27df1bc7]
[ Info: Precompiling RDatasets [ce6b1742-4840-55fa-b093-852dadbb1d8b]
size(smarket) = (1250, 9)
names(smarket) = ["Year", "Lag1", "Lag2", "Lag3", "Lag4", "Lag5", "Volume", "Today", "Direction"]
[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall ~/.julia/packages/PyCall/L0fLP/src/numpy.jl:67
[ Info: For silent loading, specify `verbosity=0`.
import MLJLinearModels[ Info: Precompiling MLJLinearModels [6ee0df7b-362f-4a72-a706-9e79364fb692]
 ✔
[ Info: Training Machine{LogisticClassifier,…}.
false_positive(cm) = 598
accuracy(ŷ, y) |> r3 = 0.518
accuracy(cm) |> r3 = 0.518
precision(ŷ, y) |> r3 = 0.518
recall(ŷ, y) |> r3 = 0.992
f1score(ŷ, y) |> r3 = 0.681
[ Info: Training Machine{LogisticClassifier,…}.
[ Info: Training Machine{LogisticClassifier,…}.
UnivariateFinite{OrderedFactor{2}, String, UInt8, Float64}[UnivariateFinite{OrderedFactor{2}}(Down=>0.5, Up=>0.5), UnivariateFinite{OrderedFactor{2}}(Down=>0.495, Up=>0.505)][ Info: For silent loading, specify `verbosity=0`.
import MLJMultivariateStatsInterface[ Info: Precompiling MLJMultivariateStatsInterface [1b6a4a23-ba22-4f51-9698-8599985d3728]
 ✔
[ Info: Training Machine{BayesianLDA,…}.
[ Info: For silent loading, specify `verbosity=0`.
import MLJMultivariateStatsInterface ✔
[ Info: Training Machine{LDA,…}.
[ Info: For silent loading, specify `verbosity=0`.
import MLJScikitLearnInterface[ Info: Precompiling MLJScikitLearnInterface [5ae90465-5518-4432-b9d2-8a1def2f0cab]
 ✔
[ Info: Training Machine{BayesianQDA,…}.
[ Info: For silent loading, specify `verbosity=0`.
import NearestNeighborModels[ Info: Precompiling NearestNeighborModels [636a865e-7cf4-491e-846c-de09b730eb36]
 ✔
[ Info: Training Machine{KNNClassifier,…}.
[ Info: Updating Machine{KNNClassifier,…}.
#No 5474
#Yes 348
[ Info: Training Machine{Standardizer,…}.
[ Info: Training Machine{KNNClassifier,…}.
[ Info: Training Machine{LogisticClassifier,…}.
([-0.2, 0.0, 0.2, 0.4000000000000001, 0.6000000000000001, 0.8, 1.0000000000000002, 1.2000000000000002], PyCall.PyObject[PyObject Text(0, -0.2, '−0.2'), PyObject Text(0, 0.0, '0.0'), PyObject Text(0, 0.2, '0.2'), PyObject Text(0, 0.4000000000000001, '0.4'), PyObject Text(0, 0.6000000000000001, '0.6'), PyObject Text(0, 0.8, '0.8'), PyObject Text(0, 1.0000000000000002, '1.0'), PyObject Text(0, 1.2000000000000002, '1.2')])
```
</details>

the most likely explanation is that you did not set up your environment properly as @ablaom's comment suggests.

PS: I can sympathise with frustration over seemingly non-working packages, but when writing angry reports with no details bear in mind that the people who will read (and potentially act upon) it, are volunteers who do this, often in their free time, because they believe in a better ecosystem for Julia. Someone like @ablaom has spent countless hours developing MLJ. Criticism and detailed bug reports are welcome, being disrespectful isn't.

**Comment by JuanVargas** [comment]
Hi Folks, thank you for your response to my report. On my side this is what
I found:

1. I had an inconsistency regarding the python installed on my system
(Ubuntu 22.04 LTS). That version of Linux comes with Python 3.10.4 built
under GCC 11.2.0, which was released on 2021_0728.  To be consistent with
my previous work, I installed Anaconda3 and upgraded it to python 3.10.4. I
discovered that unfortunately that Anaconda upgrade uses GCC 7.5, which was
released on 2019_1114. Now in retrospect I suspect this is what created a
host of other issues when I was testing the Julia code, so I dropped the
conda version of python3 and stayed with the python3 version that came with
Ubuntu 22.04.

2. Once that happened, I downloaded the file  ISL-lab-4.tar.gz into its own
directory, which is
      /home/juan/code/julia/LearnMLJ/ISL-lab-4

2. Extracted the files, moved to the ISL-lab-4 folder

3. Ran Julia and gave the include("tutorial")

4. I was able to complete the tutorial, but only after I imported the
following packages, which were not in tutorial.jl:
   Pkg.add("MLJMultivariateStatsInterface")
   Pkg.add("Distances")
   Pkg.add("MLJScikitLearnInterface")

5. One comment: I went through the exercise of trying Julia mostly because
I was hoping to gain a performance increase on the ML projects by using
Julia directly instead of Python. Now that I see that MLJ is using python3
for some of the algos I guess I will need to reconsider and think twice if
it is worth the trouble.

Thank you for your help.
Juan E. Vargas

**Comment by tlienart** [comment]
> I went through the exercise of trying Julia mostly because I was hoping to gain a performance increase on the ML projects by using Julia directly instead of Python. Now that I see that MLJ is using python3 for some of the algos I guess I will need to reconsider and think twice if it is worth the trouble.

This has been discussed time and again and is in the docs too. The primary aim of MLJ is to provide the glue that binds a whole ML project together, not to reimplement every model in Julia (though some are). It would be stupid not to allow working with sklearn models. 

I'd invite you to read the MLJ docs and the FAQ in there. Though it sounds like bare sklearn is sufficient for your needs.

I'll close this as there's no issue with the current repo.

**Comment by JuanVargas** [comment]
Hi Thibaut,  Thank you for your response.

Yes I read the docs where the intent of MLJ is discussed. I am using Julia
to leverage the performance gains and design advantages of a modern
language.  I  find it difficult to understand the rationale of using Julia
as a front end for algos written in Python.  Perhaps it is just a personal
preference, but I prefer the simplicity of  using the algos in Python with
a front end written in Python, and for the same reason, I prefer using
algos written in Julia with a front end written in Julia.

Again, thank you, Juan

**Comment by tlienart** [comment]
The Algos you're referring to are not mostly written in python but in C.

Anyway if you've come to MLJ hoping to see all basic ML models implemented in Julia, then you're in the wrong place. MLJ encourages devs to implement models in Julia and interface with MLJ which makes them widely available. But it does not aim to own and maintain these implementations itself.

A significant number of models are indeed available via Julia libraries, these are complemented with scikit learn ones which was already available via scikitlearn.jl and it wouldn't have made sense not to also expose that to users.

Anyway, it looks like MLJ might  not be for you (in fact, I'm not even sure Julia is for you either, if the only thing you're interested in is speed) so I suggest we leave this here since in any case it's not the right repo to discuss MLJ.

I'd suggest to go to discourse if you want to have a general discussion on the topics that seem to bother you.
