### ISSUE TITLE
Banner missing when viewing with Safari

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#225]
Using Safari Version 15.6.1 (17613.3.9.1.16) today gives this:

![Screen Shot 2024-04-29 at 9 27 13 AM](https://github.com/JuliaAI/DataScienceTutorials.jl/assets/30517088/b9f1e32e-a75d-455d-b4cf-d9d580eab86e)

In Chrome the banner is fine.

@EssamWisam Can you reproduce this in some version of Safari?

**Comment by EssamWisam** [comment]
@ablaom 
Have just tried on Safari now and was able to reproduce. I assume that this didn't happen to you on Safari before the folder-reorg PR, right?

Because after some debugging it seems that Safari's JS interpreter doesn't support `import navItems from '../../routes.json' assert {type: 'json'};` which I knew was a hacky solution, given Franklin's setup, to import the JSON containing the navigation bar data. 

That said, it works fine on Microsoft Edge (where I have been testing as well).

Once you confirm, I can immediately and as a temporary measure put `routes.json` in the deep `lib` folder (like it was before the reorg) and come back to this later to see if `JSON` can be imported in a better way with Franklin (that was the best I found back then).

**Comment by ablaom** [comment]
While, I can't say for certain, I think the issue only postdates the re-org. At one point I did have working banners.

**Comment by ablaom** [comment]
> Once you confirm, I can immediately and as a temporary measure put routes.json in the deep lib folder (like it was before the reorg) and come back to this later to see if JSON can be imported in a better way with Franklin (that was the best I found back then).

Sounds like a plan. Just be sure to open an issue to flag future action.

**Comment by EssamWisam** [comment]
Alright. I deployed the hotfix and it works now on my Safari (though it was first likely caching the old files).

**Comment by ablaom** [comment]
I can confirm the fix at my end.
